# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configure.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='configure.proto',
  package='proj1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x63onfigure.proto\x12\x05proj1\" \n\x02m1\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0c\n\x04\x62ody\x18\x02 \x01(\tb\x06proto3'
)




_M1 = _descriptor.Descriptor(
  name='m1',
  full_name='proj1.m1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='proj1.m1.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='proj1.m1.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['m1'] = _M1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

m1 = _reflection.GeneratedProtocolMessageType('m1', (_message.Message,), {
  'DESCRIPTOR' : _M1,
  '__module__' : 'configure_pb2'
  # @@protoc_insertion_point(class_scope:proj1.m1)
  })
_sym_db.RegisterMessage(m1)


# @@protoc_insertion_point(module_scope)
