#include <iostream>
#include <vector>
#include "dna.h"
using namespace std;

int main() {

	// DNAreader a("ATCGACT","TACGC",2,0.5,1);
	string a = "CTGGGCTAAAAGGTCCCTTAGCCTATTTAGAAAAATGGGCCATTAGGAAATTGCAAGGAAGAACCATTCGTGAGAGGGATTAGCTGAGCTCTTTTGACTCTCTAATCACCCCTCCGTGCT";
	string b = "CCTCACCTGAAGTGTCCAGCAAATACACCAAGGGTGACGCAGGACAAGCATGAGCCATTCATACTGCTGCAACCAGAGAGAGGGAGCAGGAAAATGAGACAGGGAGGGGGCCAAAT";
	string c = "ACGTACGTACGT";
	string d = "ACGTACGTACGTACGT";
	DNAreader f(a,b,2,1,2);
	return 0;



}